language: java

services:
   - mongodb

jdk:
  - oraclejdk8
  
after_success:
- mkdir -p target/upload
- cp target/*capsule-fat*.jar target/upload
- codecov
deploy:
  provider: s3
  access_key_id: $S3_KEY
  secret_access_key: $S3_SECRET
  bucket: tilosdeploy
  acl: public_read
  local_dir: target/upload
  skip_cleanup: true
before_install:
  - pip install --user codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a4142a9c138817fe9ffb
    on_success: always
    on_failure: always
    on_start: never